### PR TITLE
SLING-11924 disallow the serialization of a ResourceResolver

### PR DESCRIPTION
**Pull request by joerghoh**

### CODE REVIEW

**Comment by joerghoh** [comment]
Right now my primary focus is on stability, that means not breaking the deserialization process, irrespective of any security or performance aspects. And I only found this happening for the ResourceResolver.

Extending that beyond the single case of a ResourceResolver is interesting and helpful to prevent the disclosure of implementation details, but not in my scope right now. Can you create a dedicated ticket for that?

**Comment by stefanseifert** [comment]
my point is that the new OSGi configuration proposed in this PR can never be removed again once released without breaking backward compatibility. so, if we want to make this configurable, i would love to see a more flexible solution not only for this narrow use case. but that's only my opinion.

**Comment by joerghoh** [comment]
@stefanseifert Sounds reasonable.

So let me re-design that code a bit that its the public interface (that means: PID names and OSGI configuration) supports more than just the ResourceResolver, but the implementation will only support the RR for the moment. We can expand it in the future then.

WDYT?

**Comment by stefanseifert** [comment]
yes, this would be a better path to a step-by-step approach

**Comment by joerghoh** [comment]
I made it more generic and extendable, leaving the implementation mostly as is and just support the ResourceResolver.

@stefanseifert does that meet your ideas?

**Pull request merged**
